# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

codecov: true

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - nightly

notifications:
  email: false

env:
  global:
    - DOCUMENTER_DEBUG=true
  jobs:
    - JULIA_NUM_THREADS=1
    - JULIA_NUM_THREADS=3

jobs:
  allow_failures:
    - julia: nightly
    - env: JULIA_NUM_THREADS=3
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
  exclude:
    - os: osx
      env: JULIA_NUM_THREADS=3
    - os: windows
      env: JULIA_NUM_THREADS=3

